#!/bin/bash

# mark - Help System
# Comprehensive help functionality

show_help() {
    echo "mark - AI Prompt Templating Tool"
    echo "================================"
    echo ""
    echo "A powerful tool for generating AI prompts from templates with:"
    echo "  • Placeholders: {{variable_name}}"
    echo "  • File inclusion: {{@file_path}}"
    echo "  • Conditional blocks: {{#if condition}}...{{/if}}"
    echo "  • Loop/iteration blocks: {{#each array}}...{{/each}}"
    echo ""
    echo "Usage: mark <command> [options]"
    echo ""
    echo "Commands:"
    echo "  generate <template> [data]    Generate a prompt from a template"
    echo "  list                          List recently generated prompts"
    echo "  clear                         Clear logs"
    echo "  config <action> [key] [val]   Manage configuration"
    echo "  template <action> [args]      Manage templates"
    echo "  help                          Show this help message"
    echo "  version                       Show version information"
    echo ""
    echo "Use 'mark help <command>' for more information about a specific command."
    echo ""
}

show_detailed_help() {
    case "$1" in
        generate|g)
            echo "Generate Command"
            echo "================"
            echo ""
            echo "Generate a prompt from a template file."
            echo ""
            echo "Usage:"
            echo "  mark generate <template> [data_file]"
            echo ""
            echo "Arguments:"
            echo "  template    The template file to use"
            echo "  data_file   Optional data file for variable substitution"
            echo ""
            echo "Template Syntax:"
            echo "  • Placeholders: {{variable_name}} - Replaced with variable values"
            echo "  • File inclusion: {{@file_path}} - Include content from another file"
            echo "  • Conditional blocks: {{#if condition}}...{{/if}} - Include content if condition is true"
            echo "  • Loop blocks: {{#each array}}...{{/each}} - Iterate over array items"
            echo ""
            echo "Data File Format:"
            echo "  Simple key=value format:"
            echo "    name=John Doe"
            echo "    age=30"
            echo "    city=New York"
            echo ""
            echo "Examples:"
            echo "  mark generate my_template.md"
            echo "  mark generate my_template.md my_data.md"
            ;;
        list|l)
            echo "List Command"
            echo "============"
            echo ""
            echo "List recently generated prompts."
            echo ""
            echo "Usage:"
            echo "  mark list"
            echo ""
            echo "Shows the last 10 entries in the log file."
            ;;
        clear|c)
            echo "Clear Command"
            echo "============="
            echo ""
            echo "Clear all logs."
            echo ""
            echo "Usage:"
            echo "  mark clear"
            echo ""
            echo "Removes all entries from the log file."
            ;;
        config|cfg)
            echo "Config Command"
            echo "=============="
            echo ""
            echo "Manage configuration options."
            echo ""
            echo "Usage:"
            echo "  mark config <action> [key] [value]"
            echo ""
            echo "Actions:"
            echo "  set <key> <value>    Set a configuration value"
            echo "  get <key>            Get a configuration value"
            echo "  list                 List all configuration values"
            echo ""
            echo "Configuration Options:"
            echo "  LOG_FILE             Log file location (default: ~/.mark.log)"
            echo "  TEMPLATE_DIR         Template directory (default: ~/.mark/templates)"
            echo "  TEMPLATE_EXT         Default template extension (default: .md)"
            echo "  DATA_EXT             Data file extension (default: .md)"
            echo ""
            echo "Examples:"
            echo "  mark config set editor nvim"
            echo "  mark config get editor"
            echo "  mark config list"
            ;;
        template|t)
            echo "Template Command"
            echo "================"
            echo ""
            echo "Manage templates."
            echo ""
            echo "Usage:"
            echo "  mark template <action> [args]"
            echo ""
            echo "Actions:"
            echo "  list                    List all templates"
            echo "  show <name>             Show template content"
            echo "  new <name>              Create a new template"
            echo "  edit <name>             Edit a template"
            echo "  delete <name>           Delete a template"
            echo "  rename <old> <new>      Rename a template"
            echo ""
            echo "Examples:"
            echo "  mark template list"
            echo "  mark template new my_template.md"
            echo "  mark template edit my_template.md"
            ;;
        *)
            show_help
            ;;
    esac
}